import fs from 'fs';
import path from 'path';
import sharp from 'sharp';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PUBLIC_DIR = path.join(__dirname, '../public');
const OUTPUT_DATA_FILE = path.join(__dirname, '../src/data/imagePlaceholders.ts');

async function processImages() {
  console.log('Starting image optimization...');
  const files = fs.readdirSync(PUBLIC_DIR);
  
  const placeholders = {};
  
  for (const file of files) {
    if (file.match(/\.(jpg|jpeg|png)$/i)) {
      const inputPath = path.join(PUBLIC_DIR, file);
      const ext = path.extname(file);
      const baseName = path.basename(file, ext);
      
      const webpName = `${baseName}.webp`;
      const webpPath = path.join(PUBLIC_DIR, webpName);
      
      // 1. Generate WebP if it doesn't exist
      if (!fs.existsSync(webpPath)) {
        console.log(`Converting ${file} to WebP...`);
        await sharp(inputPath)
          .webp({ quality: 80 })
          .toFile(webpPath);
      }
      
      // 2. Generate Base64 Blur Placeholder (10x10)
      console.log(`Generating placeholder for ${file}...`);
      const buffer = await sharp(inputPath)
        .resize(20, 20, { fit: 'inside' })
        .webp({ quality: 20 })
        .toBuffer();
        
      const base64 = `data:image/webp;base64,${buffer.toString('base64')}`;
      
      // Store mapping for both original name and webp name
      placeholders[`/${file}`] = base64;
      placeholders[`/${webpName}`] = base64;
    }
  }
  
  // Write the mapping to a TS file
  const tsContent = `// Automatically generated by scripts/optimize-images.mjs\n\nexport const imagePlaceholders: Record<string, string> = ${JSON.stringify(placeholders, null, 2)};\n`;
  
  fs.writeFileSync(OUTPUT_DATA_FILE, tsContent);
  console.log('Image optimization complete! Placeholders saved to src/data/imagePlaceholders.ts');
}

processImages().catch(console.error);
