/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NannkaTvRouteImport } from './routes/nannka-tv'
import { Route as NannKMediaRouteImport } from './routes/nann-k-media'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BluesDuFleuveRouteImport } from './routes/blues-du-fleuve'
import { Route as BilletterieRouteImport } from './routes/billetterie'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInscriptionsRouteImport } from './routes/admin/inscriptions'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin/articles.index'
import { Route as AdminArticlesNewRouteImport } from './routes/admin/articles.new'

const NannkaTvRoute = NannkaTvRouteImport.update({
  id: '/nannka-tv',
  path: '/nannka-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const NannKMediaRoute = NannKMediaRouteImport.update({
  id: '/nann-k-media',
  path: '/nann-k-media',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BluesDuFleuveRoute = BluesDuFleuveRouteImport.update({
  id: '/blues-du-fleuve',
  path: '/blues-du-fleuve',
  getParentRoute: () => rootRouteImport,
} as any)
const BilletterieRoute = BilletterieRouteImport.update({
  id: '/billetterie',
  path: '/billetterie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInscriptionsRoute = AdminInscriptionsRouteImport.update({
  id: '/inscriptions',
  path: '/inscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/billetterie': typeof BilletterieRoute
  '/blues-du-fleuve': typeof BluesDuFleuveRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRoute
  '/nann-k-media': typeof NannKMediaRoute
  '/nannka-tv': typeof NannkaTvRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/inscriptions': typeof AdminInscriptionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billetterie': typeof BilletterieRoute
  '/blues-du-fleuve': typeof BluesDuFleuveRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRoute
  '/nann-k-media': typeof NannKMediaRoute
  '/nannka-tv': typeof NannkaTvRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/inscriptions': typeof AdminInscriptionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/billetterie': typeof BilletterieRoute
  '/blues-du-fleuve': typeof BluesDuFleuveRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRoute
  '/nann-k-media': typeof NannKMediaRoute
  '/nannka-tv': typeof NannkaTvRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/inscriptions': typeof AdminInscriptionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/billetterie'
    | '/blues-du-fleuve'
    | '/contact'
    | '/formations'
    | '/nann-k-media'
    | '/nannka-tv'
    | '/admin/announcements'
    | '/admin/contacts'
    | '/admin/inscriptions'
    | '/admin/login'
    | '/admin/'
    | '/admin/articles/new'
    | '/admin/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billetterie'
    | '/blues-du-fleuve'
    | '/contact'
    | '/formations'
    | '/nann-k-media'
    | '/nannka-tv'
    | '/admin/announcements'
    | '/admin/contacts'
    | '/admin/inscriptions'
    | '/admin/login'
    | '/admin'
    | '/admin/articles/new'
    | '/admin/articles'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/billetterie'
    | '/blues-du-fleuve'
    | '/contact'
    | '/formations'
    | '/nann-k-media'
    | '/nannka-tv'
    | '/admin/announcements'
    | '/admin/contacts'
    | '/admin/inscriptions'
    | '/admin/login'
    | '/admin/'
    | '/admin/articles/new'
    | '/admin/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BilletterieRoute: typeof BilletterieRoute
  BluesDuFleuveRoute: typeof BluesDuFleuveRoute
  ContactRoute: typeof ContactRoute
  FormationsRoute: typeof FormationsRoute
  NannKMediaRoute: typeof NannKMediaRoute
  NannkaTvRoute: typeof NannkaTvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nannka-tv': {
      id: '/nannka-tv'
      path: '/nannka-tv'
      fullPath: '/nannka-tv'
      preLoaderRoute: typeof NannkaTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nann-k-media': {
      id: '/nann-k-media'
      path: '/nann-k-media'
      fullPath: '/nann-k-media'
      preLoaderRoute: typeof NannKMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blues-du-fleuve': {
      id: '/blues-du-fleuve'
      path: '/blues-du-fleuve'
      fullPath: '/blues-du-fleuve'
      preLoaderRoute: typeof BluesDuFleuveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billetterie': {
      id: '/billetterie'
      path: '/billetterie'
      fullPath: '/billetterie'
      preLoaderRoute: typeof BilletterieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inscriptions': {
      id: '/admin/inscriptions'
      path: '/inscriptions'
      fullPath: '/admin/inscriptions'
      preLoaderRoute: typeof AdminInscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminInscriptionsRoute: typeof AdminInscriptionsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminInscriptionsRoute: AdminInscriptionsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BilletterieRoute: BilletterieRoute,
  BluesDuFleuveRoute: BluesDuFleuveRoute,
  ContactRoute: ContactRoute,
  FormationsRoute: FormationsRoute,
  NannKMediaRoute: NannKMediaRoute,
  NannkaTvRoute: NannkaTvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
