/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NannkaTvRouteImport } from './routes/nannka-tv'
import { Route as NannKMediaRouteImport } from './routes/nann-k-media'
import { Route as BluesDuFleuveRouteImport } from './routes/blues-du-fleuve'
import { Route as IndexRouteImport } from './routes/index'

const NannkaTvRoute = NannkaTvRouteImport.update({
  id: '/nannka-tv',
  path: '/nannka-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const NannKMediaRoute = NannKMediaRouteImport.update({
  id: '/nann-k-media',
  path: '/nann-k-media',
  getParentRoute: () => rootRouteImport,
} as any)
const BluesDuFleuveRoute = BluesDuFleuveRouteImport.update({
  id: '/blues-du-fleuve',
  path: '/blues-du-fleuve',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blues-du-fleuve': typeof BluesDuFleuveRoute
  '/nann-k-media': typeof NannKMediaRoute
  '/nannka-tv': typeof NannkaTvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blues-du-fleuve': typeof BluesDuFleuveRoute
  '/nann-k-media': typeof NannKMediaRoute
  '/nannka-tv': typeof NannkaTvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blues-du-fleuve': typeof BluesDuFleuveRoute
  '/nann-k-media': typeof NannKMediaRoute
  '/nannka-tv': typeof NannkaTvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blues-du-fleuve' | '/nann-k-media' | '/nannka-tv'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blues-du-fleuve' | '/nann-k-media' | '/nannka-tv'
  id: '__root__' | '/' | '/blues-du-fleuve' | '/nann-k-media' | '/nannka-tv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BluesDuFleuveRoute: typeof BluesDuFleuveRoute
  NannKMediaRoute: typeof NannKMediaRoute
  NannkaTvRoute: typeof NannkaTvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nannka-tv': {
      id: '/nannka-tv'
      path: '/nannka-tv'
      fullPath: '/nannka-tv'
      preLoaderRoute: typeof NannkaTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nann-k-media': {
      id: '/nann-k-media'
      path: '/nann-k-media'
      fullPath: '/nann-k-media'
      preLoaderRoute: typeof NannKMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blues-du-fleuve': {
      id: '/blues-du-fleuve'
      path: '/blues-du-fleuve'
      fullPath: '/blues-du-fleuve'
      preLoaderRoute: typeof BluesDuFleuveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BluesDuFleuveRoute: BluesDuFleuveRoute,
  NannKMediaRoute: NannKMediaRoute,
  NannkaTvRoute: NannkaTvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
